# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\usuario\OneDrive\Documentos\semestre 2021-3\ciencias 2.2\Recorrido\ventanaR.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 419)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boton_Borrarpuntos = QtWidgets.QPushButton(self.centralwidget)
        self.boton_Borrarpuntos.setGeometry(QtCore.QRect(80, 350, 91, 23))
        self.boton_Borrarpuntos.setObjectName("boton_Borrarpuntos")
        self.boton_Lista = QtWidgets.QPushButton(self.centralwidget)
        self.boton_Lista.setGeometry(QtCore.QRect(300, 350, 121, 23))
        self.boton_Lista.setObjectName("boton_Lista")
        self.boton_Dibujar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_Dibujar.setGeometry(QtCore.QRect(540, 350, 101, 23))
        self.boton_Dibujar.setObjectName("boton_Dibujar")
        self.Contenedor = QtWidgets.QFrame(self.centralwidget)
        self.Contenedor.setGeometry(QtCore.QRect(39, 30, 661, 301))
        self.Contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Contenedor.setObjectName("Contenedor")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boton_Borrarpuntos.setText(_translate("MainWindow", "Borrar Puntos"))
        self.boton_Lista.setText(_translate("MainWindow", "Lista de Adyacencia"))
        self.boton_Dibujar.setText(_translate("MainWindow", "Dibujar Recorridos"))
